### ISSUE TITLE
Missing Library

### ISSUE THREAD

**Issue by abol3z** [Esri/android-gps-test-tool#16]
The library `com.esri.android.map.MapView` is missing, is there a specific library or SDK that i should use it with this project?

**Comment by andygup** [comment]
@abol3z Yes, please note that under README > Requirements it says you'll need the ArcGIS Runtime SDK for Android. This is the toolkit that provides the mapping functionality. 

Here's the [developer docs](http://resources.arcgis.com/en/communities/runtime-android/). And here's the [download link](https://developers.arcgis.com/en/downloads/). I recommend using **version 10.2.4**. 

You'll need to create an account in order to log-in and download the SDK. Go [here](https://developers.arcgis.com/en/sign-in/) free developer account.

ArcGIS Runtime SDK for Android v10.2.5 requires Android Studio and this project is currently only supported on Eclipse. Everything should run okay on Android Studio, I just haven't had time to migrate the code and test everything.

**Comment by abol3z** [comment]
Oh!, thanks, I don't know how I missed it :)
